spring:
  application:
    name: teste_compasso
  datasource:
    url: jdbc:mysql://localhost:3306/teste_compasso?createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9999
